schema: src/graphql/schema.graphql
documents: src/**/*.gql
extensions:
  codegen:
    generates:
      src/types/graphql.gen.ts:
        plugins:
          - typescript
      src/:
        preset: near-operation-file
        presetConfig:
          extension: .gen.ts
          baseTypesPath: types/graphql.gen.ts
        plugins:
          - typescript-operations
          - typescript-react-apollo
        config:
          namingConvention:
            transformUnderscore: true
