name: Frontend CI

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: npm install
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run format
        run: npm run format
