name: Frontend CI

on:
  push:

jobs:
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install packages
        working-directory: front
        run: npm install

      - name: Run lint
        working-directory: front
        run: npm run lint

      - name: Run format
        working-directory: front
        run: npm run format
